apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: flake8-lint
spec:
  workspaces:
    - name: source
  steps:
    - name: flake8
      image: python:3.9-slim
      workingDir: $(workspaces.source.path)/../output
      script: |
        #!/bin/sh
        pip install flake8
        echo "Ejecutando flake8 en: $(pwd)"
        ls -la
        flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 service --count --max-complexity=10 --max-line-length=127 --statistics