apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: accounts-pipeline
spec:
  params:
    - name: repo-url
      type: string
    - name: revision
      type: string
      default: main
    - name: DATABASE_URI
      type: string
  workspaces:
    - name: workspace
  tasks:
    - name: clone-lint-test
      taskRef:
        name: clone-lint-test
      params:
        - name: repo-url
          value: $(params.repo-url)
        - name: revision
          value: $(params.revision)
        - name: DATABASE_URI
          value: $(params.DATABASE_URI)
      workspaces:
        - name: source
          workspace: workspace

    - name: build-image
      taskRef:
        name: buildah-unprivileged
      runAfter:
        - clone-lint-test
      params:
        - name: IMAGE
          value: us.icr.io/sn-labs-oreyesc/accounts:$(tasks.clone-lint-test.results.commit-sha)
      workspaces:
        - name: source
          workspace: workspace

    - name: deploy
      taskRef:
        name: openshift-client
      runAfter:
        - build-image
      params:
        - name: ARGS
          value:
            - apply
            - -f
            - deploy/